# Use new container infrastructure to enable caching
sudo: required
dist: trusty

# Choose a lightweight base image; we provide our own build tools.
language: generic

services:
  - docker

# GHC depends on GMP. You can add other dependencies here as well.
addons:
  apt:
    packages:
    - libgmp-dev
    - libaio1     # for oracle
    - unixodbc    # for oracle

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- ci/install-oracle.sh
- ci/load-sql.sh
- ci/install-instantclient.sh
- ci/install-ocilib.sh

#before_script:
#- docker --version
#- docker pull alexeiled/docker-oracle-xe-11g
#- docker run -d --name oracle -p 1521:1521 -v $(pwd)/sql:/etc/entrypoint-initdb.d alexeiled/docker-oracle-xe-11g


# This line does all of the work: installs GHC if necessary, build the library,
# executables, and test suites, and runs the test suites. --no-terminal works
# around some quirks in Travis's terminal implementation.
script:
- stack --no-terminal --install-ghc build --test --no-run-tests
- LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/test/test
- cat /etc/ld.so.conf

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
